### PR TITLE
support recent versions of the Fantasy Land specification

### PR DESCRIPTION
**Pull request by davidchambers**
I actually think it would be a good idea to deprecate this project and update the readme to suggest that people use [Fluture][1] instead. If you'd like to keep this project around, though, you're welcome to merge this pull request.

[1]: https://github.com/fluture-js/Fluture

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
Thanks for the PR! :slightly_smiling_face:

**Comment by davidchambers** [comment]
Could you publish v2.0.0 so I can update plaid/async-problem#31?

**Comment by Risto-Stevcev** [comment]
@davidchambers done :+1:

**Comment by davidchambers** [comment]
It looks as though you tagged an existing commit rather than updating `"version"` in __package.json__ and pushing a new tagged commit. Perhaps as a result of this v2.0.0 is not available on npm:

```console
$ npm view lazy-either versions
[ '1.0.0', '1.0.1', '1.0.2', '1.0.3' ]
```

I recommend [xyz][1] for avoiding such mishaps.


[1]: https://github.com/davidchambers/xyz

**Pull request merged**
