### PR TITLE
readme: recommend Fluture

### PR DESCRIPTION
**Pull request by davidchambers**
The wonderful thing about Fantasy Land is that two implementations of the same algebraic data type should be interchangeable. Factors such as documentation and performance differentiate libraries rather than API design.

If someone stumbles upon LazyEither we should draw her attention to [Fluture][1], which is a mature and actively developed implementation of the same algebraic data type.

[1]: https://github.com/fluture-js/Fluture

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
@davidchambers It's definitely not the same algebraic data type. Everything that Either can implement so can LazyEither, things like Bifunctor, etc. Similar to how something like LazyMaybe can implement Monoid or MonadPlus. Fluture is too generic to be able to implement those directly.

**Comment by davidchambers** [comment]
> It's definitely not the same algebraic data type.

Ah, okay. I had assumed that one could define a Bifunctor instance for `Future a b`. In fact, I see [`bimap`][1] in Fluture's readme. I'll let @Avaq clarify the matter. :)


[1]: https://github.com/fluture-js/Fluture#bimap

**Comment by Risto-Stevcev** [comment]
@davidchambers 
You obviously didn't understand my point. Does Fluture implement these in a statically typed way (no javascript bs):

(Semigroup b) => Semigroup (Either a b)
(Semiring b) => Semiring (Either a b)
Bitraversable Either
Traversable (Either a)
Bifoldable Either
Foldable (Either a)
(Bounded a, Bounded b) => Bounded (Either a b)
(Ord a) => Ord1 (Either a)
(Ord a, Ord b) => Ord (Either a b)
(Eq a) => Eq1 (Either a)
(Eq a, Eq b) => Eq (Either a b)
(Show a, Show b) => Show (Either a b)
Extend (Either e)
Monad (Either e)
Bind (Either e)
Alt (Either e)
Applicative (Either e)
Apply (Either e)
Bifunctor Either
Invariant (Either a)
Functor (Either a)

If the answer is all of the above, then I will delete this repository no questions further asked. I don't see how it possible could. If the answer is no to some of them, then it's not the same ADT.

I don't think it's a big deal to be honest, this library only has 12 stars, I don't think very many people are using this library, if anyone at all. If this is all about my contribution from async-problem with this library, please feel free to remove it from that list.

**Comment by davidchambers** [comment]
> Does Fluture implement these in a statically typed way[?]

No. Fluture is implemented in JavaScript, so doesn't provide static guarantees.

I'm confused by your comment, Risto. LazyEither is also implemented in JavaScript, is it not?

**Comment by Risto-Stevcev** [comment]
Sorry that wasn't clear. By a "statically typed way", what I meant is that the type doesn't magically change at runtime. Whatever the type is implementing at any one time doesn't magically change by invoking some function at runtime, it's implementation stays the same. In JS you could implement a fantasy land type dynamically if you wanted to and the language wouldn't stop you. The hindley milner types that fluture gives, or other libs that implement fantasy land specs, are meant to be interpreted as statically typed signatures. They're not supposed to magically change to something else at runtime. This is what I meant.

In the context of what I was referring to for that, I think fluture's Future doesn't magically implement everything Maybe does because it's passed as an argument to `fold`. From what I can tell, it's containing Maybe and Either inside the future itself and resolving it. In contrast, the type of LazyEither can/should/will implement everything the Either type does. But for example, if there were a LazyMaybe, then it could implement Monoid, which LazyEither can't do, and Future wouldn't do directly (although it can contain a Maybe inside of itself, like fluture does).

The `fold` in fluture actually should be `bifold`. Fluture has a way of converting the future to an Either or a Maybe, but the future is resolved at that point. LazyEither is always an Either type, even before it gets resolved. Fluture parameterizes Either (or Maybe) with `fold`, LazyEither implements Either directly. Fluture wouldn't be able to legitimately implement both Either and Maybe directly based on whatever is given at runtime, so they're parameterized. I mean it could, but it would be pretty strange. This is the distinction I'm seeing, but if it's not a real distinction for some reason then I'll deprecate this library.

**Comment by davidchambers** [comment]
While `Future a (Either b c)` is a valid type, I'm suggesting that `Future a b` itself has much in common with `Either a b` and can support many of the same operations.

`Future a b` and `LazyEither a b` seem equivalent to me, semantically. Because I don't see a semantic difference between the two types I can't imagine an operation which one type can support but the other type cannot. It's possible I'm overlooking a meaningful difference between the two types, of course. :)

**Comment by Risto-Stevcev** [comment]
Yeah I think the semantics is where it differs, but I could be wrong also

**Comment by davidchambers** [comment]
What got me thinking was the similarity of these [solutions][1]:

```javascript
//    concatFiles :: (String -> String) -> Future Error String
const concatFiles = path =>
  S.pipe([path,
          readFile,
          S.map(S.lines),
          S.map(S.map(path)),
          S.chain(S.traverse(Future, readFile)),
          S.map(S.joinWith(''))],
         'index.txt');
```

```javascript
//    concatFiles :: (String -> String) -> LazyEither Error String
const concatFiles = path =>
  S.pipe([path,
          readFile,
          S.map(S.lines),
          S.map(S.map(path)),
          S.chain(S.traverse(LazyEither, readFile)),
          S.map(S.joinWith(''))],
         'index.txt');
```

Thanks for merging this pull request. :)


[1]: https://github.com/plaid/async-problem

**Comment by Risto-Stevcev** [comment]
When I first wrote this, there weren't any future implementations that looked like this. You would have a `fork` method that you gave two callbacks, one for failure and one for success. I wrote this because I noticed that the data structure looked a lot like `Either`, and instead of having to give two callbacks (which I found annoying) you should be able to just give one, and the value is an Either type.

Then a little while later, Avaq was working on adapting some concepts/code from this library and folktale, and some of his own optimizations made fluture outperform folktale in his benchmarks. Specifically, I think what he did different was this:

```js
Future.reject(new Error('It broke'))
.fold(S.Left, S.Right)
.value(console.log);
```

So instead of having to give two callbacks to fork, you give it to fold instead. With LazyEither you don't have to do the `fold` part because it's an `Either` type. I think it's the exact same thing as LazyEither if the `.fold(S.Left, S.Right)` part was implicitly part of `.value`.

Though fluture is more generic for that, there are some drawbacks to doing what fluture is doing there. If you don't call `fold` before `value`, then it won't behave in an intuitive way, and which is why I kept this library around. From the fluture readme:

```
Extracts the value from a resolved Future by forking it. Only use this function if you are sure the Future is going to be resolved, for example; after using .fold(). If the Future rejects and value was used, an (likely uncatchable) Error will be thrown.
```

Which results in this potential gotcha:
```
Future.reject(new Error('It broke'))
.fold(S.Left, S.Right)
.value(console.log);
//> Left([Error: It broke])
Just like fork, value returns the Cancel function:

Future.after(300, 'hello').value(console.log)();
//Nothing will happen. The Future was cancelled before it could settle.
```

Which is only a problem because it's more generic, and LazyEither is more opinionated in that regard so it doesn't have to worry about doing that. LazyEither saves a little bit of verbosity and a potentially getting bitten by not applying the operations in the correct order.

**Comment by Risto-Stevcev** [comment]
@davidchambers Well they're both future implementations, the fact that both code snippets look the same is not surprising to me :). But before LazyEither and subsequently Fluture, you would have a `fork` at the end, rather than `value`

**Comment by davidchambers** [comment]
Thanks for elaborating, Risto. I do see differences between the way Fluture and LazyEither work at the very edge of a program (when calling `fork` or `value`). The nice thing is that the body of the program will be almost identical regardless of whether one is using Fluture or LazyEither. :)

**Comment by Risto-Stevcev** [comment]
Yeah that's true. In retrospect, I think the `fork` then `value` issue is an easily solved one: Avaq should just provide a `eitherValue` or something similar, and then it's the same thing. But I haven't been actively playing around with fantasyland and fp js for a while now as you've probably guessed, and in practice that might not be very useful sugar.

**Pull request merged**
